version: '3.9'

services:
  db_dev:
    image: "postgres:latest"
    environment:
      PGDATA: $PGDATA 
      POSTGRES_DB: $POSTGRES_DB 
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
      - './db/seed.sql:/docker-entrypoint-initdb.d/init.sql'

  admin_dev:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: $PGADMIN_DEFAULT_EMAIL
      PGADMIN_DEFAULT_PASSWORD: $PGADMIN_DEFAULT_PASSWORD    
    ports:
      - "5555:5555"
    depends_on:
      - db_dev

  api_dev:
    image: ramyferhat59/cashmanager-deploy:api_dev
    build: ./api
    ports:
      - "8000:8000"
    environment:
      POSTGRES_NAME: $POSTGRES_NAME
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD 
      COMPOSE_PROJECT_NAME: $COMPOSE_PROJECT_NAME
      DOCKER_HUB_USER: $DOCKER_HUB_USER
      DOCKER_HUB_PASS: $DOCKER_HUB_PASS
    depends_on:
      - db_dev

volumes:
  pgdata:
