# Generated by Django 4.1 on 2022-11-14 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_article_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='active',
        ),
    ]
