# Generated by Django 4.1 on 2022-11-14 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_article_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='in_stock_quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='out_stock_quantity',
        ),
        migrations.AddField(
            model_name='article',
            name='in_stock_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='out_stock_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
