# Generated by Django 4.1 on 2022-12-12 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_cart_cartarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='stripe_price_id',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='stripe_product_id',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='article',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=8),
        ),
    ]
