# Generated by Django 4.1 on 2022-12-13 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_article_stripe_price_id_article_stripe_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartarticle',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
