# Generated by Django 4.1 on 2023-01-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_article_description_alter_article_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('CR', 'Awaiting'), ('FL', 'Failed'), ('SC', 'Succeed')], default='CR', max_length=2),
        ),
    ]
