# Generated by Django 4.1 on 2023-01-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_transaction_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_email',
            field=models.CharField(default='Not provided', max_length=128),
        ),
    ]
