# Generated by Django 4.1 on 2023-01-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_remove_transaction_user_transaction_payment_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='payment_email',
            new_name='payment_user_email',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('AW', 'Awaiting'), ('FL', 'Failed'), ('SC', 'Succeeded')], default='AW', max_length=2),
        ),
    ]
