# Generated by Django 4.1 on 2023-01-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_user_email',
            field=models.CharField(default='Not provided', max_length=1000),
        ),
    ]
