version: "3.9"

services:

  db:
    container_name: cash_manager_db
    image: postgres
    environment:
      - POSTGRES_PASSWORD=secretpassword
    volumes:
      - database_volume:/var/lib/postgresql/data

  api:
    container_name: cash_manager_api
    build: .
    environment:
      - SECRET_KEY=verysecretKey
      - DEBUG=0
      - DB_NAME=postgres
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=secretpassword
      - ALLOWED_HOSTS=*
      - HOSTNAME=$HOST
    command: make runproxyversion
    depends_on:
      - db
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media

  server:
    container_name: cash_manager_server
    image: arm64v8/nginx:stable
    ports:
      - "80:80"
    depends_on:
      - api
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - ./nginx/conf/:/etc/nginx/conf.d/:ro

volumes:
  database_volume:
  static_volume:
  media_volume:
