version: "3.9"

services:

  apiservice:
    container_name: cash_manager_api
    build: .
    depends_on:
      - database
    environment:
      - SECRET_KEY=verysecretKey
      - DEBUG=0
      - DB_NAME=postgres
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=secretpassword
      - ALLOWED_HOSTS=*
      - HOSTNAME=$HOST
    command: make runproxyversion
    networks:
      - nginx_network
      - pg_network
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media

  database:
    container_name: cash_manager_database
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=secretpassword
    volumes:
      - database_volume:/var/lib/postgresql/data
    networks:
      - pg_network

  nginx:
    container_name: cash_manager_nginx
    build: ./nginx
    ports:
      - "8000:80"
      - "8000:443"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - apiservice
    restart: "on-failure"
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge
  pg_network:
    driver: bridge

volumes:
  database_volume:
  static_volume:
  media_volume: