version: "3.9"

services:

  apiservice:
    container_name: cash_manager_api
    build: .
    depends_on:
      - database
    environment:
      - SECRET_KEY=verysecretKey
      - DEBUG=0
      - DB_NAME=postgres
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=secretpassword
      - ALLOWED_HOSTS=*
      - HOSTNAME=$HOST
    command: make runproxyversion
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media

  database:
    container_name: cash_manager_database
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=secretpassword
    volumes:
      - database_volume:/var/lib/postgresql/data

  nginx:
    container_name: cash_manager_nginx
    image: arm64v8/nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - apiservice
    restart: "always"

  certbot:
    image: certbot/certbot:arm64v8-v1.32.2
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

volumes:
  database_volume:
  static_volume:
  media_volume:
