name: Cash manager development continuous delivery

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    
    - name: Build Updated Docker Compose Environment
      run: |
        cd t-dev-700-par-11-deployment/t-dev-700-par-11-deployment/api/
        docker-compose build

    - name: Stop Old Docker Compose Environment
      run: docker-compose down

    - name: Run Updated Docker Compose Environment
      run: docker-compose up -d

    - name: Remove Unused Docker Compose Environment
      run: |
        docker container prune -f
        docker image prune -f
